# hysys_config_generator.py

import config
import re
from collections import defaultdict

def select_reactor_type(parsed_data: dict) -> str:
    """
    根据解析出的数据，应用选择逻辑 8，选择最合适的反应器类型。
    返回 'Conversion', 'Equilibrium', 'Gibbs'
    """
    # 逻辑 8 的实现
    if parsed_data.get("kinetic_params_provided"): # 优先检查动力学参数
        # HYSYS 中，如果有动力学参数，通常用 CSTR/PFR (Conversion Reactor 也可以实现)
        # 这里我们先统一用 Conversion Reactor 来处理，具体是 CSTR 还是 PFR
        # 可以根据是液相还是气相进一步判断，但本次考核可能不需要这么细致
        return "Conversion"
    elif parsed_data.get("conversion") is not None or parsed_data.get("yield") is not None:
        # 如果提供了转化率/收率，使用 Conversion Reactor
        return "Conversion"
    elif parsed_data.get("equilibrium_info_provided"):
        # 如果是可逆反应，或提供了平衡信息，使用 Equilibrium Reactor
        return "Equilibrium"
    elif parsed_data.get("reactor_type_hint") == "Gibbs": # 如果用户明确提到了 Gibbs
         return "Gibbs"
    else:
        # 默认或需要进一步判断的情况，可以考虑 Gibbs Reactor
        # 或者根据补充信息 9 进行判断，例如高转化率、复杂反应、产物未知等
        # 如果信息不足，可以默认回退到 Conversion Reactor 或提示用户
        print("Warning: Could not definitively determine reactor type. Defaulting to Conversion Reactor.")
        return "Conversion"

def generate_hysys_script(parsed_data: dict, reactor_type: str) -> str:
    """
    根据解析数据和选定的反应器类型，生成 HYSYS 的操作脚本。
    这是一个非常简化的示例，实际 HYSYS 脚本会非常复杂。
    """
    script_lines = []
    script_lines.append("! HYSYS Automation Script - Generated by AI")
    script_lines.append("! Reactor Type: " + reactor_type)

    # --- 1. 定义物流 (Materials) ---
    script_lines.append("\n! Define Components and Fluid Package")
    # 假设我们使用 Peng-Robinson (PR) 物性方法
    script_lines.append("DEFINE PROPERTY PACKAGE PR")
    script_lines.append("ADD COMPONENT CH4 METHANE") # 示例: 甲烷
    script_lines.append("ADD COMPONENT H2 HYDROGEN") # 示例: 氢气
    script_lines.append("ADD COMPONENT CO CARBON-MONOXIDE") # 示例: 一氧化碳
    script_lines.append("ADD COMPONENT H2O WATER") # 示例: 水
    script_lines.append("DEFINE MATERIAL BAL METHANE H2O") # 定义物流信息
    # 这里的组分信息需要根据 parsed_data 和 config.COMPONENT_MAPPING 来动态生成

    # --- 2. 定义进料物流 (Feed Stream) ---
    # 示例：假设进料是甲烷和水，摩尔比 1:1，温度 25C，压力 1 atm
    feed_temp = parsed_data.get("temperature", "25 C")
    feed_pressure = parsed_data.get("pressure", "1 atm")
    # 进料流的定义需要更精细，包括组分比例，这里简化处理
    script_lines.append(f"DEFINE STREAM FEED {feed_temp} {feed_pressure} VAPOR")
    script_lines.append("SET FEED COMPOSITION METHANE 0.5 H2O 0.5") # 假设摩尔比 1:1

    # --- 3. 创建反应器 ---
    reactor_name = "MyReactor"
    script_lines.append(f"\n! Create Reactor: {reactor_type}")

    if reactor_type == "Conversion":
        script_lines.append(f"ADD CONVERSION REACTOR {reactor_name}")
        script_lines.append(f"SET REACTOR {reactor_name} TYPE CONVERSION")
        # 配置反应参数 (需要详细的解析逻辑)
        if parsed_data.get("conversion") is not None:
            script_lines.append(f"SET REACTOR {reactor_name} CONVERSION METHANE {parsed_data['conversion']}%")
        # 假设反应是 CH4 + H2O -> CO + 3H2
        # 这里需要根据 parsed_data 生成具体的反应方程式和收率/选择性
        script_lines.append("ADD REACTION R1 METHANE + H2O = CO + 3 H2")
        script_lines.append("SET REACTION R1 TYPE EXTENT") # 反应类型
        script_lines.append("ADD REACTION SET RS1")
        script_lines.append("ADD REACTION TO RS1 R1")
        script_lines.append(f"SET REACTOR {reactor_name} REACTION SET RS1")

    elif reactor_type == "Equilibrium":
        script_lines.append(f"ADD EQUILIBRIUM REACTOR {reactor_name}")
        script_lines.append(f"SET REACTOR {reactor_name} TYPE EQUILIBRIUM")
        # 配置平衡参数 (需要详细的解析逻辑)
        # 假设反应是 CH4 + H2O <=> CO + 3 H2
        script_lines.append("ADD REACTION R1 METHANE + H2O = CO + 3 H2")
        script_lines.append("SET REACTION R1 TYPE EQUILIBRIUM")
        # 这里需要根据 parsed_data 提供 Ka 或 Gibbs Free Energy
        # script_lines.append("SET REACTION R1 EQUILIBRIUM CONSTANT")
        script_lines.append("ADD REACTION SET RS1")
        script_lines.append("ADD REACTION TO RS1 R1")
        script_lines.append(f"SET REACTOR {reactor_name} REACTION SET RS1")

    elif reactor_type == "Gibbs":
        script_lines.append(f"ADD GIBBS REACTOR {reactor_name}")
        script_lines.append(f"SET REACTOR {reactor_name} TYPE GIBBS")
        # Gibbs Reactor 通常不需要明确指定反应，它会计算达到最小 Gibbs 自由能时的产物分布

    # --- 4. 连接物流和反应器 ---
    script_lines.append(f"\n! Connect Stream and Reactor")
    script_lines.append(f"CONNECT FEED TO {reactor_name} INLET")
    script_lines.append(f"DEFINE STREAM {reactor_name}-OUTLET {reactor_name} OUTLET")

    # --- 5. 设置操作条件 (如果未在物流中定义) ---
    if parsed_data.get("temperature") and reactor_type != "Gibbs": # Gibbs Reactor 内部自动计算
        script_lines.append(f"SET REACTOR {reactor_name} TEMPERATURE {feed_temp}")
    if parsed_data.get("pressure") and reactor_type != "Gibbs":
        script_lines.append(f"SET REACTOR {reactor_name} PRESSURE {feed_pressure}")

    # --- 6. 运行模拟 ---
    script_lines.append("\n! Run Simulation")
    script_lines.append("SOLVE")

    # --- 7. 保存结果 ---
    # HYSYS 脚本语言本身不能直接写文件，这部分需要通过外部命令或 HYSYS COM 接口实现
    # 这里我们假设 HYSYS 运行完毕后，我们再从本地读取其输出文件
    # 或者，可以在 HYSYS 中设置保存 case 文件，然后我们下载 case 文件进行解析
    # 这是一个简化的例子，实际需要根据 HYSYS 的自动化能力来设计
    script_lines.append(f"! After SOLVE, HYSYS may save results to a case file or output stream.")
    script_lines.append("! We will download and parse the results externally.")
    # script_lines.append(f"SAVE CASE \"{config.REMOTE_TEMP_DIR}/generated_case.hys\"") # 示例：保存 case 文件

    return "\n".join(script_lines)

# --- 示例用法 ---
if __name__ == "__main__":
    # 假设已经解析好的数据
    example_parsed_data = {
        "reactants": ["methane", "water"],
        "products": ["hydrogen", "carbon-monoxide"],
        "temperature": "800 C",
        "pressure": "10 atm",
        "conversion": 95.0,
        "yield": None,
        "selectivity": None,
        "kinetic_params_provided": True, # 假设提供转化率就代表有动力学相关信息
        "equilibrium_info_provided": True,
        "reactor_type_hint": "Conversion"
    }
    reactor_type = select_reactor_type(example_parsed_data)
    print(f"Selected Reactor Type: {reactor_type}")
    hysys_script = generate_hysys_script(example_parsed_data, reactor_type)
    print("\nGenerated HYSYS Script:\n", hysys_script)